app:
  name: reembolsocoders
spring:
  application:
    name: reembolsocoders
  datasource:
    url: jdbc:postgresql://localhost/reembolso
    username: postgres
    password: 123
  jpa:
    generate-ddl: true
server:
  port: ${PORT:8080}
jwt:
  header: Authorization
  expires_in: 86400
  mobile_expires_in: 86400
  secret: SREDOC
  pass_secret: DOC
management:
  security:
    enable: false